name: Tanishq Jasoria
description: Manners Maketh Man
meta_description: "I am a Senior Undergraduate student at the Department 
                   of Mathematics, IIT Kharagpur pursuing my Bachelor’s 
                   and Master’s degree in Mathematics and Computing."
meta_tags: "tanishq, jasoria, iit, kharagpur, systems, security, network
            secure system development, software development"
title: Senior Undergraduate, Department of Mathematics
aboutPage: true
about_profile_image: assets/images/avatar.png
darkmode: false
about_content: "I am a curious person who is always excited about
exploring the unknown, and this is why I have delved into seemingly 
diverse fields. I have worked on various projects involving myself 
in secure software development, systems security, robotics, deep 
learning and embedded systems. I believe in the current world scenario,
having specialization in one niche field is not as rewarding as 
developing an appreciation and understanding for a melange of various inter-twined skills.

My primary research interest is in the area of Systems Research, especially
in building and analyzing secure systems. I envision my future research to 
span across some interrelated sub-areas of networked and distributed computing 
systems. The unifying theme of the research will be the construction of reliable 
and secure computing platforms with a focus on data privacy. Additionally, I have an
interest in working in the area of decentralized systems to make the role of 
\"trusted third party\" obsolete. I believe that the invocation or assumption in a 
security protocol design of a \"trusted third party\" controlled by a third party 
constitutes the introduction of a security hole into that design"

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-seo-tag

paginate: 20
domain_name: 'tanishqjasoria.github.io'
google_analytics: 'UA-155175818-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

#social-icons
facebook: tanishqjasoria
twitter: jasoriatanishq
instagram: tanishqjasoria
linkedin: tanishqjasoria
github: tanishqjasoria
email: jasoriatanishq@gmail.com
website: tanishqjasoria.github.io

# Details for the RSS feed generator
url:            'https://tanishqjasoria.github.io'
author:         'Tanishq Jasoria'
authorTwitter:  'jasoriatanishq'

permalink:       /:year/:title/


sass:
    sass_dir: _sass
    style: compressed

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
